quipper/sbpayment.rb

lib/sbpayment/response.rb
spec/requests/api/credit_spec.rb

The have other results. And clarify only `'OK'` and `'NG'` makes a bit confusion, I feel :bow:

Remove Sbpayment::Response#{ok|ng}_result?

---

README.md
lib/sbpayment/api/au/cancel_refund.rb
lib/sbpayment/api/docomo/simplified_cancel_refund.rb

* Rename class name. I misunderstood.
* `Sbpayment::API::Docomo::SimplifiedRefundRequest` -> `Sbpayment::API::Docomo::SimplifiedCancelRefundRequest`
* `Sbpayment::API::Au::RefundRequest` -> `Sbpayment::API::Au::CancelRefundRequest`
* Fix field definition: https://github.com/quipper/sbpayment.rb/commit/ff3cfb079dbab0cc68a607928dea353a0940f01c

Rename class name

---

README.md
lib/sbpayment/api/au/cancel_refund.rb
lib/sbpayment/api/credit/authorization.rb
lib/sbpayment/api/credit/cancel_authorization.rb
lib/sbpayment/api/credit/commit.rb
lib/sbpayment/api/credit/create_customer.rb
lib/sbpayment/api/credit/delete_customer.rb
lib/sbpayment/api/credit/inquire_authorization.rb
lib/sbpayment/api/credit/partly_refund.rb
lib/sbpayment/api/credit/re_authorization.rb
lib/sbpayment/api/credit/read_customer.rb
lib/sbpayment/api/credit/refund.rb
lib/sbpayment/api/credit/update_customer.rb
lib/sbpayment/api/docomo/simplified_cancel_refund.rb
lib/sbpayment/api/softbank/authorization.rb
lib/sbpayment/api/softbank/cancel_refund.rb
lib/sbpayment/api/softbank/commit.rb
lib/sbpayment/configuration.rb
lib/sbpayment/link/purchase_request.rb
spec/sbpayment/configuration_spec.rb

* As I said here https://github.com/quipper/sbpayment.rb/pull/29, if we set `allow_multiple_service_id = true`, it immediately raises an error, so [current implementation](https://github.com/quipper/sbpayment.rb/pull/15) is wrong and it's not intended.
*  Regarding spec, even if we have to treat multiple service id, `service_id` is not the only key we care. Other configuration also need to change. So my original idea was wrong: https://gist.github.com/banyan/391c754f8efbb49dbe09
* Tested and it does not break.

Discard allow_multiple_service_id

---

lib/sbpayment/api/au/cancel_refund.rb

This is not covered in spec of SBPS as of 2016-03-04.
I had an error, then asked SBPS guy and turned out SBPS's spec was wrong :sweat_smile:

Add cancel_target_month to Sbpayment::API::Au::CancelRefundRequest

---

README.md
lib/sbpayment/configuration.rb
lib/sbpayment/request.rb
spec/sbpayment/configuration_spec.rb

I would like to control whether to retry or not. So I was going to add `enable_retry` option to configuration.
However it's also useful to controll retry counts, so I added `retry_max_counts` option.
Default behavior is same as before this pull request.
BTW thank you for creating this gem. 👍

Implement to controll retry counts

---

README.md
lib/sbpayment/configuration.rb
lib/sbpayment/request.rb
spec/requests/api/timeout_spec.rb
spec/sbpayment/configuration_spec.rb

I would like to control Faraday's timeout options, so this pull request supports both open_timeout and timeout options.
This pull request is based on #46's branch.
So I will rebase master branch after #46 was merged If this pull request was accepted.

Support Faraday's timeout options

---

lib/sbpayment/api/credit/sales.rb

This branch fixes a bug in api/credit/sales.rb.
- API::Credit::SalesRequest has class: PayOptionManage, but the correspondent key definition is not defined in the class. 
The test for this fix is not implemented yet, please let me know if you have suggestion about it.

bugfix: credit sales key: pay_option_manage is not defined

---

circle.yml

ref: https://www.ruby-lang.org/en/news/2016/11/21/ruby-2-3-3-released/

Bump 2.3.n ruby version in CI from 2.3.1 to 2.3.3

---

spec/spec_helper.rb

I didn't track the reason yet, but without this PR makes rspec/CI failure in current master 🤔

Clarify to load securerandom in specs

---

spec/spec_helper.rb

I didn't know which code and/or dependency using this global variable...
📝 CI failure is another issue, it requires https://github.com/quipper/sbpayment.rb/pull/52

Remove unused global variable in test

---

lib/sbpayment/link/routine_entry.rb

One day we received the following email from SBPS and it compelled me to check the diff between `D01-n` specifications.
```
－－－－－－－－－－－－－－－－－－－－－－－－－－－－ 
【お知らせ】オンライン決済ASP仕様関連資料改定のご案内
－－－－－－－－－－－－－－－－－－－－－－－－－－－－ 
※当ご連絡はSBPSオンライン決済ASP利用のお客様向けご案内となります。
お客様各位 
拝啓　時下ますますご清栄のこととお慶び申し上げます。 
平素は弊社サービスをご利用いただき、誠にありがとうございます。 
オンライン決済ASPの仕様関連資料について改定を行いました。
以下の通りご連絡申し上げますので、ご確認ください。
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　敬具
記
■変更対象仕様書
　C004_リンク型システム仕様書（継続課金（定期・従量）申込要求）
　
■変更内容
　各仕様書の改定履歴をご確認ください。
　
■公開日
　2017年4月28日
■資料入手方法
　開発者支援サイト「Developer Console」仕様書ダウンロードページ
　https://developer.sbpayment.jp/document/show
■その他
　上記改定対象仕様書をご利用の場合は、必ず今回の修正版（20170428版）を再度ご確認ください。
```
After checking the latest document ([C004_リンク型システム仕様書（継続課金（定期・従量）申込要求）_20170428.pdf](https://github.com/quipper/sbpayment.rb/files/993167/C0 …

Remove `free_csv` field from Sbpayment::Link::RoutineEntity

---

lib/sbpayment/api_error/feature_modules.rb
lib/sbpayment/api_error/fields.rb
spec/sbpayment/errors_spec.rb

Some SBPS API errors can be retried and it can be determined via the error type. So these predicator will be useful, I think.

Provide #retryable? in API errors when they have error type

---

spec/sbpayment/link/update_report_spec.rb
spec/sbpayment/link/update_result_spec.rb

```
WARNING: Shared example group 'prepare update result params' has been previously defined at:
/Users/kachick/repos/quipper/sbpayment.rb/spec/sbpayment/link/update_report_spec.rb:3
...and you are now defining it at:
/Users/kachick/repos/quipper/sbpayment.rb/spec/sbpayment/link/update_result_spec.rb:3
The new definition will overwrite the original one.
```
🙈

Fix shared_context definition

---

README.md
lib/sbpayment.rb
lib/sbpayment/api/payeasy/cancel.rb
lib/sbpayment/api/payeasy/notice.rb
lib/sbpayment/api/payeasy/payment.rb
lib/sbpayment/api/webcvs/cancel.rb
lib/sbpayment/api/webcvs/notice.rb
lib/sbpayment/callback_factory.rb
lib/sbpayment/callback_request.rb
lib/sbpayment/callback_response.rb
spec/fixtures/payeasy_cancel_request.xml
spec/fixtures/payeasy_cancel_response.xml
spec/fixtures/payeasy_cancel_response_with_error.xml
spec/fixtures/payeasy_notice_request.xml
spec/fixtures/payeasy_notice_response.xml
spec/fixtures/payeasy_notice_response_with_error.xml
spec/fixtures/webcvs_cancel_request.xml
spec/fixtures/webcvs_cancel_response.xml
spec/fixtures/webcvs_cancel_response_with_error.xml
spec/fixtures/webcvs_notice_request.xml
spec/fixtures/webcvs_notice_response.xml
spec/fixtures/webcvs_notice_response_with_error.xml
spec/requests/api/callback_spec.rb
spec/requests/api/payeasy_spec.rb
spec/vcr_cassettes/_webcvs-read-payment-result.yml
spec/vcr_cassettes/payeasy-payment-request.yml
spec/vcr_cassettes/webcvs-read-payment-result.yml

Hajime Mashite. Let me PR a new component that handles Payeasy and Webcvs APIs.
The feature allows us to work with Payeasy/Webcvs requests, as well as incoming callbacks from SBPayment.
This PR is 99.9% based on the efforts made by @motchang (please refer to #45 for the previous PR) , which I happened to take over a last bit thanks to his kind offer.
It's been running stably on our web services for months, and we'd be happy if we could contribute to the original gem with these features :)

Implement Payeasy and Webcvs APIs

---

spec/sbpayment/errors_spec.rb

This pattern should get item summary from https://github.com/quipper/sbpayment.rb/blob/60d2a4a9524fef58ada3c75fee897e3ffd531d53/lib/sbpayment/api_error/definitions.rb#L300-L302, but currently failed.
Sorry I didn't get the error cause yet 🙇 , this PR just adds the spec.

Add a filing spec

---

.circleci/config.yml
gemfiles/faraday-0.16/Gemfile
gemfiles/faraday-0.16/Gemfile.lock
gemfiles/faraday-0.17/Gemfile
gemfiles/faraday-0.17/Gemfile.lock
gemfiles/faraday-1.0/Gemfile
gemfiles/faraday-1.0/Gemfile.lock
lib/sbpayment/request.rb
spec/requests/api/proxy_spec.rb

In faraday 1.0+, we can't use `Faraday::Connection#proxy` to set proxy settings. Instead of it, we can use `Faraday::Connection#proxy=`. This method has been introduced since 0.13.0.
https://github.com/lostisland/faraday/commit/d18cc04be5c179b1b22b9dd1004030dd43b0ca58#diff-ec23de93634c9f1330648fecdfd152dfR288-R290
This PR fixes warnings like this with faraday < 1.0:
```
Warning: use of proxy(new_value) to set connection proxy have been DEPRECATED and will be removed in Faraday 1.0
```
In addition to that, this PR configures matrix tests against faraday and ruby.

Use proxy=() instead of removed proxy()

---

.rspec
spec/requests/api/au_spec.rb
spec/requests/api/callback_spec.rb
spec/requests/api/credit_spec.rb
spec/requests/api/customer_spec.rb
spec/requests/api/docomo_spec.rb
spec/requests/api/payeasy_spec.rb
spec/requests/api/proxy_spec.rb
spec/requests/api/softbank_spec.rb
spec/requests/api/timeout_spec.rb
spec/requests/api/webcvs_spec.rb
spec/sbpayment/configuration_spec.rb
spec/sbpayment/crypto_spec.rb
spec/sbpayment/decode_parameters_spec.rb
spec/sbpayment/errors_spec.rb
spec/sbpayment/link/purchase_report_spec.rb
spec/sbpayment/link/purchase_request/validators_spec.rb
spec/sbpayment/link/purchase_result_spec.rb
spec/sbpayment/link/update_report_spec.rb
spec/sbpayment/link/update_result_spec.rb
spec/sbpayment/parameter_definition_spec.rb
spec/sbpayment/shallow_hash_spec.rb
spec/sbpayment/time_util_spec.rb
spec/spec_helper.rb

* この行が使われていませんでした。
* 検知しやすくするように ruby の warning が `bundle exec rspec` 時に出るようにしました

Remove unused code from spec

---

.circleci/config.yml

https://circleci.com/docs/ja/2.0/sample-config/ には `--path` 指定の例が記載されているのですが、CIを見ているとこんなwarningが出ていました
```
#!/bin/bash -eo pipefail
bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path …
```

Care bundler deprecation in CI

---

spec/requests/api/au_spec.rb
spec/requests/api/callback_spec.rb
spec/requests/api/credit_spec.rb
spec/requests/api/customer_spec.rb
spec/requests/api/docomo_spec.rb
spec/requests/api/payeasy_spec.rb
spec/requests/api/proxy_spec.rb
spec/requests/api/softbank_spec.rb
spec/requests/api/timeout_spec.rb
spec/requests/api/webcvs_spec.rb
spec/sbpayment/configuration_spec.rb
spec/sbpayment/crypto_spec.rb
spec/sbpayment/decode_parameters_spec.rb
spec/sbpayment/errors_spec.rb
spec/sbpayment/link/purchase_report_spec.rb
spec/sbpayment/link/purchase_request/validators_spec.rb
spec/sbpayment/link/purchase_result_spec.rb
spec/sbpayment/link/update_report_spec.rb
spec/sbpayment/link/update_result_spec.rb
spec/sbpayment/parameter_definition_spec.rb
spec/sbpayment/shallow_hash_spec.rb
spec/sbpayment/time_util_spec.rb
spec/spec_helper.rb

https://relishapp.com/rspec/rspec-core/v/3-9/docs/configuration/zero-monkey-patching-mode これを enable にするPRです。
初期の頃は should から変わるの嫌だ的意見も多かったと思うのですが最近殆ど聞かないのと、既存の spec が全部 should 使ってなかったようなのでいっそ縛っておいたほうが良いかなと。
https://relishapp.com/rspec/rspec-core/v/3-9/docs/configuration/global-namespace-dsl の disable と両方onにした方が良いのか？ と最初は思ったんですが 
https://github.com/rspec/rspec-core/blob/ecb65d2d4ea7b381472e3084f45e2da94e00ce91/lib/rspec/core/configuration.rb#L1844-L1846
これ見る限り、  `Zero monkey patching mode` が  `Global namespace DSL の disable` も内包しているようです。

Enable `Zero monkey patching mode` in rspec

---

.circleci/config.yml

latest 指定しておけば常に最新のrubyでtestしてくれるという認識なので合ってますかね？一応入れとくと安心かなと
ref: https://circleci.com/docs/ja/2.0/circleci-images/#ruby

Update CI rubies and test in latest too

---

lib/sbpayment/api_error/fields.rb
lib/sbpayment/errors.rb
sbpayment.gemspec

https://github.com/quipper/sbpayment.rb/blob/71348e1628f50aeaf134dbc20a8c43d67d979f54/.circleci/config.yml#L31-L34
今のCIで check している version 的にも Official でのサポート状況的にも、とりあえず 2.4 以上対応ということにしてしまっていいのかなと思いました。
https://www.ruby-lang.org/ja/news/2020/04/05/support-of-ruby-2-4-has-ended/ (2.4も end ではある)

Prefer Regexp#match? and drop ruby ~2.4 support

---

lib/sbpayment/errors.rb
spec/sbpayment/errors_spec.rb

https://github.com/quipper/sbpayment.rb/pull/20 の中で、 大体の sbpayment.rb 由来の例外を `Sbpayment::Error` のサブクラスに変更しました。
その時、このパースエラーは特に触らなかったのですが、 `CSV::MalformedCSVError` や  `JSON::ParserError` の存在を考えると、ここはやはり Sbpayment::Error のサブクラスにしておいた方が良いかなと今更になって思いました。
https://docs.ruby-lang.org/ja/latest/class/CSV=3a=3aMalformedCSVError.html
https://docs.ruby-lang.org/ja/latest/class/JSON=3a=3aParserError.html
とはいえ互換性を壊す変更且つそれほど有意義な変更かと言われると自分にも自信が無いので、気になって一応PR出しておいたぐらいの温度感です。 機会があれば検討していただけると 🙏 
(例外名にもあまりこだわりはありません。 あえていうと `Malformed` 的な表現が意味的にぴったり来る気はするんですが、他で多そうなParserErrorという名前にしてしまいました。)

Raise specific error instead of ArgumentError for parsing failure

---

.circleci/config.yml
CHANGELOG.md
sbpayment.gemspec

EOL ruby 2.5
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-5-9-released/

drop ruby 2.5 support
