quipper/sbpayment.rb

lib/sbpayment.rb
lib/sbpayment/api/authorization.rb
lib/sbpayment/api/create_customer.rb
lib/sbpayment/api/delete_customer.rb
lib/sbpayment/api/inquire_authorization.rb
lib/sbpayment/api/re_authorization.rb
lib/sbpayment/api/read_customer.rb
lib/sbpayment/api/update_customer.rb
lib/sbpayment/decrypt_parameters.rb
lib/sbpayment/parameter_definition.rb
lib/sbpayment/response.rb
spec/requests/credit_spec.rb
spec/sbpayment/parameter_definition_spec.rb

Follow up to https://github.com/quipper/sbpayment.rb/pull/5

Allow not proc in default value, avoid to require dependencies as globally

---

lib/sbpayment/api/au/refund.rb
lib/sbpayment/api/credit/authorization.rb
lib/sbpayment/api/credit/cancel_authorization.rb
lib/sbpayment/api/credit/commit.rb
lib/sbpayment/api/credit/create_customer.rb
lib/sbpayment/api/credit/delete_customer.rb
lib/sbpayment/api/credit/inquire_authorization.rb
lib/sbpayment/api/credit/partly_refund.rb
lib/sbpayment/api/credit/re_authorization.rb
lib/sbpayment/api/credit/read_customer.rb
lib/sbpayment/api/credit/refund.rb
lib/sbpayment/api/credit/update_customer.rb
lib/sbpayment/api/docomo/simplified_refund.rb
lib/sbpayment/api/softbank/authorization.rb
lib/sbpayment/api/softbank/commit.rb
lib/sbpayment/api/softbank/refund.rb
lib/sbpayment/configuration.rb
lib/sbpayment/link/purchase_request.rb
spec/sbpayment/configuration_spec.rb

Re-opened from https://github.com/quipper/sbpayment.rb/pull/14#issuecomment-149111931
@banyan suggested to this idea. Thank you!
ref: https://gist.github.com/banyan/391c754f8efbb49dbe09

Intercept default service_id for multiple service_id apps

---

README.md
example/purchase_result.rb
lib/sbpayment/configuration.rb
spec/sbpayment/configuration_spec.rb
spec/sbpayment/link/purchase_result_spec.rb

Add description for  and simplified api for consistency to other apis.

Change api

---

lib/sbpayment.rb
lib/sbpayment/configuration.rb
lib/sbpayment/link.rb
spec/sbpayment/configuration_spec.rb
spec/sbpayment/crypto_spec.rb
spec/sbpayment/decode_parameters_spec.rb
spec/sbpayment/errors_spec.rb
spec/sbpayment/parameter_definition_spec.rb
spec/sbpayment/shallow_hash_spec.rb

Follow #19

---

lib/sbpayment/api/softbank/commit.rb

Remove sps_transaction_id

---

spec/sbpayment/link/update_report_spec.rb

ref: https://github.com/quipper/sbpayment.rb/pull/25#issuecomment-163198666

Add update_report_spec imported from update_result_spec

---

lib/sbpayment/api/webcvs/payment.rb
lib/sbpayment/api/webcvs/read_payment_result.rb
spec/requests/api/webcvs_spec.rb
spec/vcr_cassettes/webcvs-read-payment-result.yml

Implements webcvs payment result API (MG01-00101-701).
Unfortunately, SBPS's sandbox (API type) seems not working well for webcvs API payment type (payment API result returns "70122999" error code)

Implement webcvs read payment result API (MG01-00101-701)

---

example/routine_entry.rb
lib/sbpayment/link/routine_entry.rb

This is the endpoint for D01-1 and the name "RoutineEntry"  is taken from sbps specification.

Add Sbpayment::Link::RoutineEntry

---

README.md
lib/sbpayment/api/softbank/cancel_refund.rb

From `Sbpayment::API::Softbank::RefundRequest` to `Sbpayment::API::Softbank::CancelRefundRequest`.
Same as https://github.com/quipper/sbpayment.rb/pull/23

Rename class name

---

lib/sbpayment/api/webcvs/payment.rb
lib/sbpayment/api/webcvs/read_payment_result.rb
lib/sbpayment/link/routine_entry.rb
lib/sbpayment/link/update_request.rb

Follow up to https://github.com/quipper/sbpayment.rb/pull/35

Adapt with other service id

---

lib/sbpayment/api/credit/re_authorization.rb

Similar of https://github.com/quipper/sbpayment.rb/pull/40

Fix a key type of ST01-00113-101

---

README.md
lib/sbpayment/api/credit/sales.rb
spec/requests/api/credit_spec.rb
spec/vcr_cassettes/authorization-commit-and-sales.yml

just Impremented ST02-00201-101
check pleasae :bow:

Implement Sbpayment::API::Credit::SalesRequest

---

spec/requests/api/credit_spec.rb
spec/vcr_cassettes/authorization_with_invalid_dealing_type.yml

fix pended test in credit_spec.rb
- add VCR xml file which returns NG response.
- group OK/NG tests into each describe block.

uncomment pending rspec test in credit_spec

---

README.md
lib/sbpayment/api/credit/authorization_token.rb
lib/sbpayment/api/credit/create_customer_token.rb
lib/sbpayment/api/credit/sales.rb
lib/sbpayment/api/credit/update_customer_token.rb
lib/sbpayment/version.rb
spec/requests/api/credit_spec.rb
spec/requests/api/customer_spec.rb
spec/vcr_cassettes/authorization-with-token.yml
spec/vcr_cassettes/customer-api-create-with-token.yml
spec/vcr_cassettes/customer-api-update-with-token.yml

This feature branch implements credit card payment process with token.
[motivation]
- authorization, create_customer and update_customer should be processed without sending credit card information to web application server if servers are not PCI-DSS compliant.
[other]
- In sales.rb, :processing_datetime has default value.

Credit payment request with token

---

circle.yml
spec/sbpayment/crypto_spec.rb
spec/sbpayment/parameter_definition_spec.rb

Update CI setting to follow ruby 2.4.1

---

docs/token.html

Follow up to https://github.com/quipper/sbpayment.rb/pull/62
I was thinking it'd work if I use gh-pages. but we already have gh-pages so it doesn't work: https://github.com/quipper/quipper.github.io I'll just use jsbin.com for now.

Add comment for backup

---

.circleci/config.yml

- Make it run test against Ruby 2.5.1
- Updated Ruby version of 2.4 & 2.3
- Tidied up `config.yml`

Update ruby version for CI

---

spec/sbpayment/errors_spec.rb

Fix some typos

---

README.md
sbpayment.gemspec

```
弊社ソフトバンク・ペイメント・サービス株式会社は、2019年1月1日より
商号（社名）を「SBペイメントサービス株式会社」に変更いたします。
```
seems like they've changed the name.

s/Softbank Payment Service/SB Payment Service/

---

.circleci/config.yml

Ruby 2.3.x is already ended the support

Update CI rubies

---

CHANGELOG.md
lib/sbpayment/version.rb

Bump to v0.11.0

---

CHANGELOG.md

We also should require including changelog entry for future PRs.  What do you think?

Add changelogs for #93, #94 and #117

---

README.md

https://github.com/quipper/sbpayment.rb/issues/133 に書いたような開発環境構築のトラブルについて、自分だったら欲しかったなと思う記述を足しておきました。

Add Docker development section in README

---

README.md
lib/sbpayment/api/au/simplified_cancel.rb
spec/requests/api/au_spec.rb
spec/vcr_cassettes/au-simplified-cancel.yml

auかんたん決済:継続課金(簡易)解約要求 の実装
機能IDは `ST02-00302-402`
参考にした仕様書 D205_API型システム仕様書（auかんたん決済）_20190101.pdf

Cancel Simplified Au Request

---

README.md
lib/sbpayment/api/docomo/simplified_cancel.rb
spec/requests/api/docomo_spec.rb
spec/vcr_cassettes/docomo-simplified-cancel.yml

ドコモ払い 継続課金（簡易）解約要求 `ST02-00302-401` の実装
参考にした仕様書 `D204_API型システム仕様書（ドコモ払い）_20190101.pdf`

Cancel Simplified Docomo Request

---

README.md
lib/sbpayment/api/credit/simplified_cancel.rb
spec/requests/api/credit_spec.rb
spec/vcr_cassettes/credit-simplified-cancel.yml

クレジットカード決済 継続課金(簡易)解約要求 `ST02-00302-101` の実装
実装時に参考にした仕様書 `D101_API型システム仕様書（クレジットカード決済）_20190628.pdf`

Cancel Simplified Credit Request

---

README.md
lib/sbpayment/api/softbank/commit.rb
lib/sbpayment/api/softbank/sales.rb

下記件に関して、もしかしたら既存実装で漏れがあったかもしれないです。
https://github.com/quipper/sbpayment.rb/pull/125#discussion_r577361085
お手すきでご確認お願い致します。

Change Softbank::CommitRequest to Softbank::SalesRequest

---

lib/sbpayment/api/au/sales.rb
lib/sbpayment/api/docomo/sales.rb
lib/sbpayment/api/softbank/commit.rb
lib/sbpayment/api/softbank/sales.rb

Related to https://github.com/quipper/sbpayment.rb/pull/125 , https://github.com/quipper/sbpayment.rb/pull/141

Move PayOptionManage to each inner class of Request

---

lib/sbpayment/errors.rb
spec/sbpayment/errors_spec.rb

https://github.com/quipper/sbpayment.rb/pull/38 で やりかけた Exception の修正PRです。 🙇 
基本的に https://github.com/quipper/sbpayment.rb/pull/71 で pending にしておいた spec が通ることを確認しつつ、同様のパターンも一応一件追加しておきました。
Exception 周りは色々と厄介なコードになってしまっていて申し訳ないのですが、自分がSBPSを殆ど触らなくなったこともあり仕様がわからず、根本的に手を入れなおす自信はありません、これで勘弁していただけると嬉しいです 🙇

Fix some APIError item summary

---

.circleci/config.yml
gemfiles/faraday-1.4/Gemfile
gemfiles/faraday-1.4/Gemfile.lock
sbpayment.gemspec

CI does not run for the latest faraday version.
https://github.com/quipper/sbpayment.rb/tree/master/gemfiles

Update faraday version

---

.circleci/config.yml
CHANGELOG.md
sbpayment.gemspec

https://github.com/quipper/sbpayment.rb/issues/150

Drop ruby 2.4 support

---

.circleci/config.yml

https://github.com/quipper/sbpayment.rb/issues/160

add ruby image 3.0.2
